config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :contacts
  resources :authors
  resources :recipes 
  resources :bans
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index' 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipes = Recipe.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
      if record_saved?(@recipe)
        redirect_to @recipe, notice: 'Recipe was successfully created.' 
      else
        render :new
      end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def record_saved?(record)
      record.save
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :title, :phone, :author, :date)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form_format">

      <div class="Nome_input_create">
        <%= form.label(:name, "Nome da receita:") %>
        <%= form.text_field :name %>
      </div>
      <div class="desc_input_create">
        <%= form.label(:description, "Descrição da receita") %>
        <%= form.text_area :description %>
      </div>
      <div class="title_input_create">
        <%= form.label(:title, "Titulo livro de receita:")%>
        <%= form.text_field :title %>
      </div>
      <div class="phone_input_create">
        <%= form.label(:phone, "Telefone do autor:")%>   
        <%= form.telephone_field :phone%>
      </div>
      <div class="author_input_create">
        <%= form.label(:author, "Autor do livro:")%>
        <%= form.text_field :author%>
      </div>
      <div class="date_input_create">
        <%= form.label(:date, "Data de fabrico:")%>
        <%= form.date_field :date %>
      </div>
      <div class="submit_button_create">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<div class="show_back_editpage">
<span><%= link_to 'Show', @recipe %></span> |
<span><%= link_to 'Back', recipes_path %></span>
</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="index_title">Recipes</h1>

<table class="all_info_index">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><b>Nome:</b> <%= recipe.name %></td>
        <td><b>Descricao:</b> <%= recipe.description %></td>
        <td><b>Titulo:</b> <%= recipe.title %></td>
        <td><b>Telefone:</b> <%= recipe.phone %></td>
        <td><b>Autor:</b> <%= recipe.author %></td>
        <td><b>Data:</b> <%= recipe.date %></td>
        <div class="options_info_index">
          <td><div class="show_info_index"><%= link_to 'Show', recipe %></div></td>
          <td><div class="edit_info_index"><%= link_to 'Edit', edit_recipe_path(recipe) %></div></td>
          <td><div class="destroy_info_index"><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></div></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="new_recipe">
  <%= link_to 'New Recipe', new_recipe_path %>
</div>

<div class="back_welcome_index">
  <%= link_to 'Back to Homepage', root_path %>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p><b>Nome do Prato:</b> <%= @recipe.name %></p>
<p><b>Descricao da receita:</b> <%= @recipe.description %></p>
<p><b>Titulo:</b> <%= @recipe.title %></p>
<p><b>Telefone:</b> <%= @recipe.phone %></p>
<p><b>Autor:</b> <%= @recipe.author %></p>
<p><b>Data:</b> <%= @recipe.date %></p>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>