config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :contacts
  resources :authors
  resources :recipes 
  resources :bans
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index' 
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :gender, :age, :birth_date, :famous)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_format">
    <div class="Nome_input_create">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, id: :author_first_name %>
    </div>

    <div class="Nome_input_create">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, id: :author_last_name %>
    </div>

    <div class="gender_input_create">
      <%= form.label :gender %>
      <%= form.select(:gender, options_for_select([['male', 'male'], ['female', 'female'], ['other', 'other'], ['OMG both', 'both']])) %>
    </div>

    <div class="age_input_create">
      <%= form.label :age %>
      <%= form.number_field :age, id: :author_age %>
    </div>

    <div class="datetime_input_create">
      <%= form.label :birth_date %>
      <%= form.datetime_select :birth_date, id: :author_birth_date %>
    </div>

    <div class="famous_input_create">
      <%= form.label :famous %>
      <%= form.check_box :famous, id: :author_famous %>
    </div>

    <div class="submit_button_create">
      <%= form.submit %>
    </div>
  </div>
  
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="index_title">Authors</h1>

<table class="all_info_index">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Age</th>
      <th>Birth date</th>
      <th>Famous</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><b>1ºNome:</b> <%= author.first_name %></td>
        <td><b>ulºNome:</b> <%= author.last_name %></td>
        <td><b>Sexo:</b> <%= author.gender %></td>
        <td><b>Idade:</b> <%= author.age %></td>
        <td><b>Data Nascimento:</b> <%= author.birth_date %></td>
        <td><b>famoso?:</b> <%= author.famous %></td>
        <td><div class="show_info_index"><%= link_to 'Show', author %></td>
        <td><div class="edit_info_index"><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><div class="destroy_info_index"><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="new_recipe">
<%= link_to 'New Author', new_author_path %>
</div>

<div class="back_welcome_index">
  <%= link_to 'Back to Homepage', root_path %>
</div>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @author.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @author.age %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @author.birth_date %>
</p>

<p>
  <strong>Famous:</strong>
  <%= @author.famous %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>