config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :contacts
  resources :authors
  resources :recipes 
  resources :bans
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index' 
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :job
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @jobs = Job.all
  end

  # GET /contacts/1/edit
  def edit
    @jobs = Job.all
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, 
          :last_name, :phone_number, :email, :country, 
          :adress, :door_number, :fax, :postal_code, 
          :mobile, :registered_date, :job_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :contact_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :contact_last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number, id: :contact_phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :contact_country %>
  </div>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress, id: :contact_adress %>
  </div>

  <div class="field">
    <%= form.label :door_number %>
    <%= form.number_field :door_number, id: :contact_door_number %>
  </div>

  <div class="field">
    <%= form.label :fax %>
    <%= form.number_field :fax, id: :contact_fax %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code, id: :contact_postal_code %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.number_field :mobile, id: :contact_mobile %>
  </div>

  <div class="field">
    <%= form.label :registered_date %>
    <%= form.date_select :registered_date, id: :contact_registered_date %>
  </div>

  <div class="field">
    <%= form.label :job %>
    <%= form.collection_select(:job_id, @jobs, :id, :career_name,include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Country</th>
      <th>Adress</th>
      <th>Door number</th>
      <th>Fax</th>
      <th>Postal code</th>
      <th>Mobile</th>
      <th>Registered date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.email %></td>
        <td><%= contact.country %></td>
        <td><%= contact.adress %></td>
        <td><%= contact.door_number %></td>
        <td><%= contact.fax %></td>
        <td><%= contact.postal_code %></td>
        <td><%= contact.mobile %></td>
        <td><%= contact.registered_date %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

<div class="back_welcome_index">
  <%= link_to 'Back to Homepage', root_path %>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Country:</strong>
  <%= @contact.country %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @contact.adress %>
</p>

<p>
  <strong>Door number:</strong>
  <%= @contact.door_number %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @contact.fax %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @contact.postal_code %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact.mobile %>
</p>

<p>
  <strong>Registered date:</strong>
  <%= @contact.registered_date %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>